import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kirsten&apos;s Dev Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Link href="">Click Here</Link> */}
        <h1 className={styles.title}>Kirsten&apos;s Dev Notes</h1>
        <div className={styles.content}>
          <div className={styles.lessons}>
            <h1>Bomb-Ass Shortcuts</h1>
            <p>Some cool shortcuts that I&apos;ve learned in VS Code</p>
            <p>Coming Soon...</p>
          </div>
          <div className={styles.lessons}>
            <h1>Amazing Videos</h1>
            <p>
              Some of my favorite coding lessons. Disclaimer: These videos
              won&apos;t put you to sleep.
            </p>
            <p>Coming Soon...</p>
          </div>
          <div className={styles.lessons}>
            <h1>Helpful Articles</h1>
            <p>Useful articles that have helped me figure some things out.</p>
            <p>Coming Soon...</p>
          </div>
          <div className={styles.lessons}>
            <h1>Cool Tools</h1>
            <p>My favorite tools, extensions, and add-ons</p>
            <p>Coming Soon...</p>
          </div>
          <div className={styles.lessons}>
            <h1>Wicked Websites</h1>
            <p>
              Some of my fav sites that are just wicked cool. Simple as that.
            </p>
            <p>Coming Soon...</p>
          </div>
          <div className={styles.lessons}>
            <h1>Dope Devs</h1>
            <p>
              Some pretty cool devs who are out there doing pretty cool things.
              Def worth checking them out.
            </p>
            <p>Coming Soon...</p>
          </div>
        </div>
      </main>
    </div>
  );
}
